inquire-app/inquire/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from inquire.profiles.views import *


urlpatterns = [
    url(r'^register/$', register_user, name='register_user'),
    url(r'^register_success/$', register_success, name='register_success'),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
    url(r'^logout_success/$', logout_success, name="logout_success"),
    url(r'^profile/$', profile, name="profile"),
]

inquire-app/inquire/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('inquire.questions.urls', namespace="questions")),
    url(r'^accounts/', include('inquire.profiles.urls', namespace='profiles')),
]

inquire-app/inquire/profiles/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from inquire.profiles.managers import InquireUserManager


class UserProfile(AbstractBaseUser, PermissionsMixin):
    # id => Default
    email = models.EmailField(_('email address'), db_index=True, unique=True)
    first_name = models.CharField(_('First name'), max_length=255, blank=True)
    last_name = models.CharField(_('Last name'), max_length=255, blank=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True) 

    object_type = "profile"
    objects = InquireUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ("id",)

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    @property
    def full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

inquire-app/inquire/profiles/forms.py
from django import forms
from inquire.profiles.models import UserProfile
from django.contrib.auth.forms import UserCreationForm


class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = UserProfile
        fields = ('email', 'password1', 'password2', 'first_name', 'last_name')
        
    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_staff = False
        user.is_superuser= False

        if commit:
            user.save()
            
        return user
    
    

class ContactForm1(forms.Form):
    subject = forms.CharField(max_length=100)
    
class ContactForm2(forms.Form):
    sender = forms.EmailField()

class ContactForm3(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

inquire-app/inquire/profiles/views.py
# Create your views here.
import datetime

from django.core.urlresolvers import reverse
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from inquire.profiles.models import UserProfile
from django.http import HttpResponse
from inquire.profiles.forms import MyRegistrationForm
# from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render


def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
    return HttpResponseRedirect(reverse('profiles:logout_success'))


def logout_success(request):
    return render_to_response('profiles/logout_success.html')


def profile(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('questions:index'))
    else:
        return HttpResponse("login not successfully")
        return render_to_response('profiles/logout.html',  {})

@csrf_protect
def register_user(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('profiles:register_success'))
        
    else:
        form = MyRegistrationForm()
    args = {}
    # args.update(csrf(request))
    
    args['form'] = form
    
    return render(request, 'profiles/register.html', args)



def register_success(request):
    return render_to_response('profiles/register_success.html')

inquire-app/inquire/profiles/templates/profiles/confirm.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>
{% if success %}
    Your account has been activated and is now ready for use.  <a href='{% url 'authentication:login' %}'>Login here</a>
{% else %}{% if expired %}
    Oops!  You waited too long!  <a href='{% url 'authentication:register' %}'>Return to the login page and try again</a>
{% else %}{% if has_account %}
    You already have an account!  <a href="{% url 'list_questions' %}">Hop in the action</a>
{% endif %}
{% endif %}
{% endif %}
</body>
</html>

inquire-app/inquire/profiles/templates/profiles/logout_success.html
{% extends "base.html" %}

{% block content %}

    <h3>You have been logged out successfully. <a href='{% url 'profiles:login' %}'>Log back in</a>
    </h3>
{% endblock %}

inquire-app/inquire/profiles/templates/profiles/register.html
{% extends "base.html" %}

{% block content %}
  
  <h2>Register</h2>
  
  {% for field in form %}
    {{field.error}}

  {% endfor %}
  
{#  <form action="/accounts/register/" method="post">{% csrf_token %}#}
{#  {{form.as_p}}#}
{##}
{##}
{#  <input type="submit" value="Register" />#}
{##}
{#   </form>#}

<div class="col-md-6">
	 <form action="/accounts/register/" method="post">{% csrf_token %}
	<p><label for="id_first_name">First name :&nbsp&nbsp</label> <input class="form-control" id="id_first_name" name="first_name" type="name" /></p>
	<p><label for="id_last_name">Last name :&nbsp&nbsp</label> <input class="form-control" id="id_last_name" name="last_name" type="name" /></p>
	<p><label for="id_email">Email:   </label> <input class="form-control" id="id_email" name="email" type="email" /></p>
	<p><label for="id_password1">Password:</label> <input class="form-control" id="id_password1" name="password1" type="password" /></p>
	<p><label for="id_password2">Re-password :&nbsp&nbsp</label> <input class="form-control" id="id_password2" name="password2" type="password" /></p>

	  <input class="btn btn-success" type="submit" value="Register" />

	  </form>
</div>
  
{% endblock %}

inquire-app/inquire/profiles/templates/profiles/register_success.html
{% extends "base.html" %}

{% block content %}

  <h2>You have registered!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}