inquire-app/inquire/questions/urls.py
from django.conf.urls import url

from inquire.questions import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^ask/$', views.goto_add_page, name='ask'),
    url(r'^add_question/$', views.add_question, name='ask_question'),
    url(r'^(?P<question_id>\d+)/answer/$', views.goto_answer_page, name='answer'),
    url(r'^(?P<question_id>\d+)/add_answer/$', views.add_answer, name='answer_question'),
    url(r'^(?P<question_id>\d+)/edit_question_page/$', views.edit_question_page, name='edit_question_page'),
    url(r'^(?P<question_id>\d+)/edit_question/$', views.edit_question, name='edit_question'),
    url(r'^(?P<question_id>\d+)/(?P<answer_id>\d+)/edit_answer_page/$', views.edit_answer_page, name='edit_answer_page'),
    url(r'^(?P<question_id>\d+)/(?P<answer_id>\d+)/edit_answer/$', views.edit_answer, name='edit_answer'),
    url(r'^(?P<tag_id>\d+)/question_group_by_tag/$', views.tag_handler, name='tag_handler'),
    url(r'^(?P<question_id>\d+)/rss/$', views.rss, name='rss'),
]

inquire-app/inquire/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('inquire.questions.urls', namespace="questions")),
    url(r'^accounts/', include('inquire.profiles.urls', namespace='profiles')),
]

inquire-app/inquire/questions/models.py
from django.db import models

from inquire.profiles.models import UserProfile


class Tag(models.Model):
    tag = models.CharField(max_length=100, unique=True)

    object_type = "tag"

    def __str__(self):
        return self.tag


class Question(models.Model):
    question_title = models.CharField(max_length=100)
    question_text = models.TextField()
    pub_date = models.DateTimeField('date published')
    modification_time = models.DateTimeField('date modified')
    author = models.ForeignKey(UserProfile, null=True)
    up_list = models.ManyToManyField(UserProfile, related_name="question_up_list")
    down_list = models.ManyToManyField(UserProfile, related_name="question_down_list")
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)
    number_of_answers = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag)

    object_type = "question"

    def __str__(self):
        return self.question_title


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    modification_time = models.DateTimeField('date modified')
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)
    net_votes = models.IntegerField(default=0)
    up_list = models.ManyToManyField(UserProfile, related_name="answer_up_list")
    down_list = models.ManyToManyField(UserProfile, related_name="answer_down_list")
    author = models.ForeignKey(UserProfile)

    object_type = "answer"

    def __str__(self):
        return self.answer_text

inquire-app/inquire/questions/views.py
from django.shortcuts import render, get_object_or_404
from inquire.questions.models import Question, Answer, Tag
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone, feedgenerator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import logging


logger = logging.getLogger(__name__)


def tag_handler(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    question_list = sorted(tag.question_set.all(), key=lambda x: x.pub_date,
                           reverse=True)
    paginator = Paginator(question_list, 10)
    page = request.GET.get('page')

    try:
        latest_question_list = paginator.page(page)
    except PageNotAnInteger:
        latest_question_list = paginator.page(1)
    except EmptyPage:
        latest_question_list = paginator.page(paginator.num_pages)

    context = {
        'latest_question_list': latest_question_list,
        'username': request.user.first_name,
        'tag': tag.tag
    }
    return render(request, 'questions/index.html', context)


def index(request):
    print('>>>>>>>>>>>>>>>>', request.user)
    question_list = Question.objects.order_by('-pub_date')
    paginator = Paginator(question_list, 10)
    page = request.GET.get('page')

    try:
        latest_question_list = paginator.page(page)
    except PageNotAnInteger:
        latest_question_list = paginator.page(1)
    except EmptyPage:
        latest_question_list = paginator.page(paginator.num_pages)

    context = {'latest_question_list': latest_question_list}

    return render(request, 'questions/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = Answer.objects.filter(question_id=question_id)

    return render(request, 'questions/detail.html', {
        'question': question,
        'answers': answers,
        'username': request.user.first_name,
        'taglist': question.tags.all
    }, )


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = Answer.objects.filter(question_id=question_id)
    return render(request, 'questions/results.html', {'question': question, 'answers': answers})


def question_vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)

    if 'VoteUpQuestion' in request.POST:
        if request.user not in p.up_list.all():
            p.up_list.add(request.user)
            p.up_votes += 1

    elif 'VoteDownQuestion' in request.POST:
        if request.user not in p.down_list.all():
            p.down_list.add(request.user)
            p.down_votes += 1

    p.save()


@login_required
def vote(request, question_id):
    if 'VoteUpQuestion' in request.POST or 'VoteDownQuestion' in request.POST:
        question_vote(request, question_id)
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))

    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = Answer.objects.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        return render(request, 'questions/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        if 'VoteUp' in request.POST:
            if request.user not in selected_choice.up_list.all():
                selected_choice.up_list.add(request.user)
                selected_choice.up_votes += 1

            selected_choice.net_votes = selected_choice.up_votes-selected_choice.down_votes
        elif 'VoteDown' in request.POST:
            if request.user not in selected_choice.down_list.all():
                selected_choice.down_list.add(request.user)
                selected_choice.down_votes += 1

            selected_choice.net_votes = selected_choice.up_votes-selected_choice.down_votes

        selected_choice.save()
        return HttpResponseRedirect(reverse('questions:detail', args=(p.id,)))


@login_required
def goto_add_page(request):
    context = {'username': request.user.first_name}
    return render(request, 'questions/ask.html', context)


def add_question(request):
    if 'Submit' in request.POST:
        new_question_title = request.POST['question_title']
        new_question_text = request.POST['question_text']
        new_question = Question(question_text=new_question_text, pub_date=timezone.now(), author=request.user,
                                modification_time=timezone.now(), question_title=new_question_title)
        tag_string = request.POST['tags']
        tags = tag_string.split(',')

        new_question.save()
        for new_tag in tags:
            new_tag_object = Tag(tag=new_tag)

            if Tag.objects.filter(tag=new_tag):
                new_question.tags.add(Tag.objects.get(tag=new_tag))
            else:
                new_tag_object.save()
                new_question.tags.add(new_tag_object)

        new_question.save()
        return HttpResponseRedirect(reverse('questions:index'))
    elif 'Cancel' in request.POST:
        return HttpResponseRedirect(reverse('questions:ask'))
    else:
        return HttpResponse("Submit new question error")


@login_required
def goto_answer_page(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    context = {'question': p, 'username': request.user.first_name}
    return render(request, 'questions/answer.html', context)


def add_answer(request, question_id):
    if 'Submit' in request.POST:
        p = get_object_or_404(Question, pk=question_id)
        new_answer_text = request.POST['answer_text']
        new_answer = Answer(answer_text=new_answer_text, pub_date=timezone.now(), author=request.user, question=p,
                             modification_time=timezone.now())
        new_answer.save()
        p.number_of_answers = len(Answer.objects.filter(question_id=question_id).all())
        p.save()
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    elif 'Cancel' in request.POST:
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    else:
        return HttpResponse("Submit new answer error")


@login_required
def edit_question_page(request, question_id):
    p = get_object_or_404(Question, pk=question_id)

    can_edit = False
    if request.user == p.author:
        can_edit = True

    context = {'question': p, "can_edit": can_edit}
    return render(request, 'questions/edit_question_page.html', context)


def edit_question(request, question_id):
    if 'Submit' in request.POST:
        p = get_object_or_404(Question, pk=question_id)
        p.question_text = request.POST['question_text']
        p.question_title = request.POST['question_title']
        p.modification_time = timezone.now()
        p.save()
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    elif 'Cancel' in request.POST:
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    else:
        return HttpResponse("Submit new answer error")


@login_required
def edit_answer_page(request, question_id, answer_id):
    p = get_object_or_404(Answer, pk=answer_id)
    q = get_object_or_404(Question, pk=question_id)

    can_edit = False
    if request.user == p.author:
        can_edit = True

    context = {'answer': p, "can_edit": can_edit, 'question': q}
    return render(request, 'questions/edit_answer_page.html', context)


def edit_answer(request, question_id, answer_id):
    if 'Submit' in request.POST:
        p = get_object_or_404(Answer, pk=answer_id)
        p.answer_text = request.POST['answer_text']
        p.modification_time = timezone.now()
        p.save()
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    elif 'Cancel' in request.POST:
        return HttpResponseRedirect(reverse('questions:detail', args=(question_id,)))
    else:
        return HttpResponse("Submit new answer error")


def rss(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = Answer.objects.filter(question_id=question_id)

    feed = feedgenerator.Rss201rev2Feed(
        title="Output question rss",
        link="",
        description=u"This is the content of all staff related to one question.",
        language=u"en",
    )

    feed.add_item(
        title=question.question_title,
        link=u"",
        description=question.question_text)

    for answer in answers:
        feed.add_item(
            title=u"answer",
            link="",
            description=answer.answer_text,)

    str=feed.writeString('utf-8')

    context = {}
    str = format(str)
    context['str'] = str

    return render(request, 'questions/rss.html', context)


def format(str):
    str = str.replace('>', '>\n')
    str = str.replace('<', '\n<')
    str = str.replace('\n\n', '\n')

    return str

inquire-app/inquire/questions/templates/questions/answer.html
{% extends "base.html" %}

{% block content %}
<h2>Question:{{ question.question_text }}</h2>
<h4>Author: {{ question.author.full_name }} </h4>
<h4>Question Creation time: {{ question.pub_date }} </h4>
<h4>Question Last updated at: {{ question.modification_time }} </h4>
<form method=POST action="{% url 'questions:answer_question' question.id %}" method=post>
    {% csrf_token %}
    What is your answer?: <br>
    <textarea class="form-control"type=text name=answer_text rows="20" cols="80"> </textarea> <br>
    <input class="btn btn-primary" type=submit name=Submit value=Submit>
    <input class="btn btn-primary" type=submit name=Cancel value=Cancel>
</form>
{% endblock %}

inquire-app/inquire/questions/templates/questions/ask.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
     <form method=POST action="{% url 'questions:ask_question' %}" method=post>
     {% csrf_token %}
     <h2>Title of your question:</h2> <br>
     <input class="form-control" type="text" name="question_title" size="50">
     <h2>Details of your question?:</h2> <br>
     <textarea class="form-control" type=text name=question_text rows="10" cols="5"> </textarea> <br>
     <h3> Please specify the tags for your question</h3>
     <input class="form-control" type="text" name="tags" placeholder="Please put your tags here and seperated by comma" size="50">
         <br>
         <br>
     <input class="btn btn-primary" type=submit name=Submit value=Submit>
     <input class="btn btn-primary" type=submit name=Cancel value=Cancel>
     </form>
    {% endif %}
{% endblock %}

inquire-app/inquire/questions/templates/questions/detail.html
{% extends "base.html" %}

{% block content %}
    <h3>Question title: {{ question.question_title }}</h3>

<h2>Question content:<br>{{ question.question_text }}</h2>
    <h5>
        <a href="{% url 'questions:edit_question_page' question.id %}"> view/modify question</a>
    </h5>

    <p class="pull-left">

        {% for tag in question.tags.all %}
            <span class="label label-success"><a href="{% url 'questions:tag_handler' tag.id %}">{{ tag }}</a></span>
        {% endfor %}
        {#                   <span class="label label-default">tag</span> <span class="label label-default">post</span></p>#}
    </p>
    <br>
    <br>
<p>Author: {{ question.author.username }} at {{ question.pub_date }}</p>
<p>Created at: {{ question.pub_date }}</p>
<p>Last update at: {{ question.modification_time }}</p>
<div>Up votes: {{ question.up_votes }}</div>
<div>Down votes: {{ question.down_votes }}</div>
    <p class="pull-left">
        <a href="{% url 'questions:rss' question.id %}">RSS</a>
    </p>
    <br>
    <br>

<form action="{% url 'questions:vote' question.id %}" method="post">
    {% csrf_token %}
<input type="submit" class ="btn btn-primary" name="VoteUpQuestion" value="Good question" />
<input type="submit" class ="btn btn-primary" name="VoteDownQuestion" value="Boring question">
</form>

   {% if answers %}
<h3> Select an answer first, then click agree or disagree </h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'questions:vote' question.id %}" method="post">
{% csrf_token %}
{% for answer in answers %}
    <h2>Answer{{ forloop.counter }}:<br>{{ answer.answer_text}}</h2>
    <h5>
        <a href="{% url 'questions:edit_answer_page' question.id answer.id%}"> view/modify answer</a>
    </h5>
    <div>Author: {{ answer.author.username }} </div>
    <div>Created at: {{ answer.pub_date }} </div>
    <div>Last updated at: {{ answer.modification_time }}</div>
    <div>Up votes: {{ answer.up_votes }}</div>
    <div>Down votes: {{ answer.down_votes }}</div>
    <div>Net positive votes: {{ answer.net_votes }} </div>
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}"><a href="{% url 'questions:edit_answer_page' question.id answer.id %}"
            >Select Answer {{ forloop.counter }}</a> </label><br />


{% endfor %}

<br>
    <input type="submit" class="btn btn-success" name="VoteUp" value="Agree" />
    <input type="submit" class="btn btn-success" name="VoteDown" value="Disagree"> <br>
</form>
<br>
<h2>You have better ideas? We need your wisdom!</h2>
<h3> <a href="{% url 'questions:answer' question.id %}">Give your answer </a> </h3>
       {% else %}

<h2>Oops! No answers yet, be the first one to answer the question!</h2>
<h3> <a href="{% url 'questions:answer' question.id %}">Give your answer </a> </h3>
{% endif %}
<br>

{% endblock %}

inquire-app/inquire/questions/templates/questions/edit_answer_page.html
{% extends "base.html" %}

{% block content %}
{% if can_edit %}
<h3> Question is: {{ question.question_text }}</h3>
<form method=POST action="{% url 'questions:edit_answer' question.id answer.id %}" method=post>
    {% csrf_token %}
    <h3 style="color: red;">Change your mind to this question? Update your answer here:</h3> <br>
    <textarea class = "form-control" type=text name=answer_text rows="20" cols="80"> {{ answer.answer_text }} </textarea> <br>
    <input class="btn btn-primary" type=submit name=Submit value=Submit>
    <input class="btn btn-primary" type=submit name=Cancel value=Cancel>
    <p>Answer is created at:{{ answer.pub_date }}</p>
    <p>Last updated at:{{ answer.modification_time }}</p>
</form>
{% else %}
    <p> <font color="red">This answer is created by {{ answer.author }}, you can only view it</font> </p>
    <p>Answer is:</p>
    <p>{{ answer.answer_text }}</p>
{% endif %}
{% endblock %}

inquire-app/inquire/questions/templates/questions/edit_question_page.html
{% extends "base.html" %}

{% block content %}
{% if can_edit %}
<form method=POST action="{% url 'questions:edit_question' question.id %}" method=post>
    {% csrf_token %}
    <h2>Titile:</h2> <br>
    <input type="text" name="question_title" value="{{ question.question_title }}" >
    <br>
    <br>
    <h2>Question content?:</h2> <br>
    <textarea class="form-control" type=text name=question_text rows="10" cols="40"> {{ question.question_text }} </textarea> <br>
    <input class="btn btn-primary" type=submit name=Submit value=Submit>
    <input class="btn btn-primary" type=submit name=Cancel value=Cancel>
</form>
{% else %}
    <p> <font color="red">This question is created by {{ question.author }}, you can only view it</font> </p>
    <p> Question is: </p>
    <p>{{ question.question_text }}</p>
{% endif %}
<p>Creation time: {{ question.pub_date }}</p>
<p>Last updated at: {{ question.modification_time }}</p>

{% endblock %}

inquire-app/inquire/questions/templates/questions/hello, world.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

        {% block content %}
        {% endblock %}

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

inquire-app/inquire/questions/templates/questions/index.html
{% extends "base.html" %}

{% block content %}

<div id="masthead">
    <div class="container">
        <div class="row">
            <div>
                {% if tag %}
                    <h1> Questions related to <span style="color:red">{{ tag }}</span>
                    </h1>
                {% else %}
                <h1>Questions</h1>
                {% endif %}
            </div>
        </div>
    </div><!-- /cont -->

</div>
{% if latest_question_list %}

    <ul>
    {% for question in latest_question_list %}
            <div class="row">
            <br>
{#            <div class="col-md-2 col-sm-3 text-center">#}
{#              <a class="story-img" href="#"><img src="//placehold.it/100" style="width:100px;height:100px" class="img-circle"></a>#}
{#            </div>#}
            <div class="col-md-10 col-sm-9">
              <li><h3>Question title: {{ question.question_title | truncatechars:500  }}.</h3></li>
              <li><h3>Question content: {{ question.question_text | truncatechars:500  }}.</h3></li>
                <p class="pull-left">

                    {% if question.tags.all %}
                        {% for tag in question.tags.all %}
                            <span class="label label-success"><a href="{% url 'questions:tag_handler' tag.id %}">{{ tag }}</a></span>
                        {% endfor %}
                    {% endif %}
                </p>
            <br>
            <br>
              <div class="row">
                <div class="col-xs-9">
                  <p> Author: {{ question.author.full_name }} </p>
                      <p>Created at: {{ question.pub_date }}</p>
                      <p>Last updated at: {{ question.modification_time }}</p>
                  <p class="lead"><button class="btn btn-default"><a href="{% url 'questions:detail' question.id %}">Read more</a></button></p>


                  <ul class="list-inline">
                  <li><a href="#">  </a> {{ question.number_of_answers }} answers now </li>
                  <li><a href="#"><i class="glyphicon glyphicon-comment"></i></a></li>
                  <li><a href="#"><i class="glyphicon glyphicon-share"></i></a></li>
                  </ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    {% endfor %}
    </ul>


{% else %}
    <p>No questions are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous %}
            <a href="?page={{ latest_question_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}.
        </span>

        {% if latest_question_list.has_next %}
            <a href="?page={{ latest_question_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

inquire-app/inquire/questions/templates/questions/results.html
<a href="{% url 'questions:index' %}">home page</a>
<h1>{{ question.question_text }}</h1>

<ul>
{% for answer in answers %}
    <li>{{ answer.answer_text }}
    </li>
    <div>{{ answer.up_votes }} users agree with this answers</div>
    <div>{{ answer.down_votes }} users disagree with this answers</div>
    <div>{{ answer.net_votes }} net votes (meaning up_votes-down_votes)</div>
{% endfor %}
</ul>

<a href="{% url 'questions:detail' question.id %}">Vote again? </a>

inquire-app/inquire/questions/templates/questions/rss.html
{% extends "base.html" %}

{% block content %}
   <p>RSS fee is for this question is</p>
    {%if str %}
        <pre>{{ str }}</pre>
    {% endif %}

{% endblock %}